name: Weekly Rebuild Outputs
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    if: github.repository == 'mtgjson/mtg-sealed-content'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute gatherer original printing generator
        run: python scripts/gatherer_original_printing_details_generator.py

      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'outputs/*.json'
          commit_message: Pull new weekly content
          push_options: --force
